kind: wasmer.io/App.v0
name: portfolio
app_id: da_n73IatAUWP1Q
owner: m-o-h-a-n-d
package: .
env:
  PHPIX_PHP_THREADS: '4'
  APP_NAME: Portfolio
  APP_ENV: production
  APP_KEY: base64:tVbgu9jDosBwyCiUPfI53HE/xWbezgJmRSuNBgffzRM=
  APP_DEBUG: 'false'
  DB_CONNECTION: mysql
  QUEUE_CONNECTION: database
  BROADCAST_CONNECTION: pusher
  PUSHER_APP_ID: '2106245'
  PUSHER_APP_KEY: 4cab289b322ba7312276
  PUSHER_APP_SECRET: 2026042e05d3065ddf12
  PUSHER_APP_CLUSTER: mt1
  PUSHER_PORT: '443'
  PUSHER_SCHEME: https
  MAIL_MAILER: resend
  RESEND_API_KEY: re_gYz22YKy_PyhmPEm6LiHJ9rEHXnD4pDoN
  MAIL_FROM_ADDRESS: contact@mohanadahmed.me
  MAIL_FROM_NAME: Mohanad Ahmed Portfolio
  AWS_ACCESS_KEY_ID: ba8cb428699c71a3b1ce6093245be2ae
  AWS_SECRET_ACCESS_KEY: 9829e984b34db777b4c0efa59dedc37edf21795c68637e4a7242f50584fa44b6
  AWS_DEFAULT_REGION: eu-west-1
  AWS_BUCKET: portfolio
  AWS_ENDPOINT: https://rkjqusyqlchjjgbiynjd.storage.supabase.co/storage/v1/s3
  AWS_USE_PATH_STYLE_ENDPOINT: 'true'
  AWS_URL: https://rkjqusyqlchjjgbiynjd.supabase.co/storage/v1/object/public/portfolio
jobs:
- name: after_deploy
  trigger: post-deployment
  action:
    execute:
      command: after_deploy
annotations:
  anybuild.run/config:
    composer_build_script: post-update-cmd
    composer_enable: true
    name: out
    node_build_command: npm run build
    node_install_inputs:
    - package.json
    node_package_manager: npm
    php_framework: laravel
    php_public_dir: public
    phpix: true
  anybuild.run/provider: laravel
  anybuild.run/version: 0.28.0
  wasmer.io/version: 7.3.0
enableDatabase: true
